
[logbegone]
	phrases = ["Disconnecting VANILLA connection attempt", "Epoll Play IO Thread ", "Channels "]
	regex = ["Disconnecting VANILLA connection attempt", "Epoll Play IO Thread ", "Channels "]

